[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
hello = "6FGZoNNrsPvEqDJzG2SNbadBQG2DynndjAktf9jzXByC"

[programs.devnet]
hello = "6FGZoNNrsPvEqDJzG2SNbadBQG2DynndjAktf9jzXByC"

[registry]
url = "https://api.apr.dev"

[provider]
# cluster = "Localnet"
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
